Feat : Département peu déployé
refugies-info/karfur pull request #2346
Opened 2024-10-21 14:43 UTC by ledjay

When the selected département isn't well deployed : 
- shows an alert on tablet
- shows a tooltip on desktop

Linear ticket : https://linear.app/refugiesinfo/issue/RI-13/rr-departement-peu-deploye

2024-10-22 07:30 UTC, kaaloo requested changes
Looks great, I found a small bug when more than one department is selected in the mobile view.

<img width="612" alt="image" src="https://github.com/user-attachments/assets/94d7c0f6-5713-4a4f-b78c-959218411bb2">

2024-10-22 08:56 UTC, matthieu-fesselier reviewed
Ok pour moi. J'ajouterai juste quelques éléments qui me semblent inutilisés que l'on peut supprimer : 
- traductions
  - notDeployedTitle
  - notDeployedWriteLink 
  - notDeployedOkLink
- composants
  - GoToDesktopModal
- images
  - rendez_vous_ordinateur
  - not_deployed_image.png

2024-10-23 16:06 UTC, ledjay commented
@matthieu-fesselier bien vu merci !

2024-10-24 08:36 UTC, ledjay commented
@kaaloo sorry missed you bug report, just fixed it right now :)

2024-10-24 09:03 UTC, kaaloo approved these changes
Nice job @ledjay !

2024-10-24 09:06 UTC, merged