WIP: Accessibility - Search page
refugies-info/karfur pull request #2406
Opened 2024-11-07 14:14 UTC by ledjay

- [x] Global breakpoints responsive from px to ems 
- [x] Search page cards zoom fixes

2024-11-19 10:43 UTC, matthieu-fesselier reviewed
Ça me paraît très bien ! 
J'ai posé 2 petites questions sur le code. 
J'ai juste 2 autres remarques : 
- quand on ouvre un filtre, et qu'on clique sur le label (et pas sur la checkbox), ça ferme le filtre. Je pense que ça va prêter à confusion avec les utilisateurs non ? 
- j'ai une erreur en console la première fois que j'ouvre un filtre (probablement pas grave) `Failed prop type: The prop `transition.timeout` is marked as required in `PopperContent`, but its value is `undefined`.`

2024-11-19 10:43 UTC, matthieu-fesselier commented on apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
> -                  title={getReadableText(props.dispositif.titreInformatif || "")}
Ça n'est pas recommandé d'avoir un title sur le lien ?

2024-11-19 10:43 UTC, matthieu-fesselier commented on apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
> +  @media (width <= 768px) {
Normal que ça ne soit pas en `em` ici?

2024-11-19 17:04 UTC, kaaloo reviewed
Difficile de bien reviewer ce PR sans faire une quick test.  J'ai relevé 6 erreurs dans wave.

<img width="364" alt="image" src="https://github.com/user-attachments/assets/1f9a87e4-24a8-4557-8214-786c8e867266">

2024-11-19 17:04 UTC, kaaloo commented on apps/client/src/components/Pages/recherche/ResultsFilter/ResultsFilter.tsx
>                        {t(option.value)}
Super la transformation en éléments HTML des filtres.  Je me pose une question sur le nombre de fiches associé à chaque item.  Est-ce ça va être clair pour un lecteur de page audio?  J'aurais tendance à utiliser plus d'aides au niveau de langue, par exemple "Anglais 181 fiches" au lieu de "Anglais 181".  Voir ajouter des textes d'aide, genre "Traduit en - ce filtre vous permet de choisir parmi les 7 traductions" etc...  J'imagine que ce sont des choses qui vont au-delà de la RGAA.

2024-11-20 13:41 UTC, ledjay commented on apps/client/src/components/UI/DispositifCard/DispositifCard.tsx
> -                  title={getReadableText(props.dispositif.titreInformatif || "")}
Je pensais tout pareil oui, mais les outils sont unanimes, si le texte du lien est identique au title c'est redondant et non recommandé du coup. J'imagine que les lecteurs audio lisent tout en double dans ce cas et que ça nuit à l'XP des malvoyants.

2024-11-20 13:46 UTC, ledjay commented on apps/client/src/components/Pages/recherche/SearchResults/SearchResults.module.scss
> +  @media (width <= 768px) {
Oh ! Good catch thanks bro !

2024-11-20 13:47 UTC, ledjay commented on apps/client/src/components/Pages/recherche/ResultsFilter/ResultsFilter.tsx
>                        {t(option.value)}
@kaaloo merci d'avoir pris le temps de tester, en effet il nous reste des erreurs liées au choix de ne pas mettre de labels sur nos inputs de recherche, j'en ai discuté avec Marianne et elle préfère ne pas revoir les choix de design à ce stade.

2024-11-20 15:32 UTC, ledjay commented
@kaaloo j'ai implémenté tes remarques sur les intitulés en mode "no styles" et j'en ai profité pour refaire une petite passe pour optimiser l'espace sur ce mode : 

<img width="1218" alt="image" src="https://github.com/user-attachments/assets/db31bd70-44a9-4e6f-af73-1ebd84e069fa">

2024-11-20 17:43 UTC, kaaloo requested changes
J'ai des cadres rouges assez chelou qui apparaissent dans le dropdown 😢 
<img width="769" alt="image" src="https://github.com/user-attachments/assets/cc57d604-0e3f-4b27-9975-75373c8e4244">

2024-11-21 06:08 UTC, kaaloo approved these changes
Bravo @ledjay ! Ce travail d'éclaireur permet d'envisager la suite du projet d'accessibilité plus sereinement.

2024-11-21 08:14 UTC, ledjay commented
> J'ai des cadres rouges assez chelou qui apparaissent dans le dropdown 😢 <img alt="image" width="769" src="https://private-user-images.githubusercontent.com/67010/388206441-cc57d604-0e3f-4b27-9975-75373c8e4244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzcxMDUsIm5iZiI6MTczMjE3NjgwNSwicGF0aCI6Ii82NzAxMC8zODgyMDY0NDEtY2M1N2Q2MDQtMGUzZi00YjI3LTk5NzUtNzUzNzNjOGU0MjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA4MTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYjhjYjZjNmE2NmUwN2NhMTI1ZTU5YzAxMjRmNzhmMDQ0MDkyNzk3MjU5OTkyMWI2OWJkY2EyNzI1YzQ4NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XTfFKIE8MdIsKWeOBXLCZf92BvNytHoL8otidqmrOAY">

Oups my bad, sorry!
Fixed :)

2024-11-21 08:14 UTC, ledjay commented
> Bravo @ledjay ! Ce travail d'éclaireur permet d'envisager la suite du projet d'accessibilité plus sereinement.

Merci, avec grand plaisir :)

2024-11-21 08:18 UTC, merged